spring:
  application:
    name: neggu
  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha

# can encrypt here : https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cors:
  allowed-origin:
    - http://localhost:8080/
  max-age: 3600

logging:
  slack:
    post-chat-url: https://slack.com/api/chat.postMessage
    post-chat-channel: 1_error_server
    token: ENC(HgB5RsUKzQ4kxSZ+JZOxCgWPu2/VFSrGkmyE1WEDkDxCWLEtSW/s8hNL5WyohYM2JFoKDypX7FVE5k5+7bf9bZIj9rrjXjGo)

oidc:
  provider:
    kakao:
      iss: https://kauth.kakao.com
      aud: ENC(9A0tR+kkLaKN+sWvP4+ZG65f6fBxRk+OcbGk99Nmz/B4R9GQra6PsYGoZuQ3LFPp)
    apple:
      iss: https://appleid.apple.com
      aud: ENC(imDf1ErWsRKty6VPe8hRNwCLGmriM4nc)
    google:
      iss: https://accounts.google.com
      aud: ENC(Y/opa61EwfoNFAaNbdJPF18I/jRgQOuNtfbt8yQaVeoNxprdIrROTuYj/Yvsoq8InT0DRBMMDm5C0WHNu5d2KPfERZ4kJhYlm+CnouF+jng1ZDh9XD8SdQ==)

open-id-connect:
  kakao: https://kauth.kakao.com
  apple: https://appleid.apple.com
  google: https://www.googleapis.com