spring:
  application:
    name: neggu

# can encrypt : https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

server:
  port: 8080