spring:
  application:
    name: neggu
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: true

server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha

# can encrypt here : https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cors:
  allowed-origin:
    - https://appleid.apple.com
    - http://localhost:8080/
  max-age: 3600

logging:
  slack:
    post-chat-url: https://slack.com/api/chat.postMessage
    post-chat-channel: 1_error_server
    token: ENC(HgB5RsUKzQ4kxSZ+JZOxCgWPu2/VFSrGkmyE1WEDkDxCWLEtSW/s8hNL5WyohYM2JFoKDypX7FVE5k5+7bf9bZIj9rrjXjGo)

oidc:
  provider:
    kakao:
      iss: https://kauth.kakao.com
      aud: ENC(9A0tR+kkLaKN+sWvP4+ZG65f6fBxRk+OcbGk99Nmz/B4R9GQra6PsYGoZuQ3LFPp)
    apple:
      iss: https://appleid.apple.com
      aud: ENC(imDf1ErWsRKty6VPe8hRNwCLGmriM4nc)
    google:
      iss: https://accounts.google.com
      aud: ENC(L0YDH1zPebW3v48+6d3IqFDaHPylWRQbNZXVvRGOaDbeGnkUnT+HXkrgsRjdkUb9zLHyP/r40GLNioCXzwYlfT3WhE2gUFZXO10MAczOw4E1aKDJnjzQAg==)

open-id-connect:
  kakao: https://kauth.kakao.com
  apple: https://appleid.apple.com
  google: https://www.googleapis.com

aws:
  s3:
    bucket: neggu-bucket
  region: ap-northeast-2
  credentials:
    accessKey: ENC(hT1fN2h7wH4z+rKOZJg8cH44XhZXdyNGkne0c1wVSEg=)
    secretKey: ENC(dsR+K6+Y2/RCJkGX+DGIHx9VEuDjX52s5k28RiSUBAX4Eb8vjGfNvFYXhVGy0St2wSuJbuxE6qw=)

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
