spring:
  application:
    name: neggu
  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha

# can encrypt here : https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cors:
  allowed-origin:
    - http://localhost:8080/
  max-age: 3600

oidc:
  provider:
    kakao:
      iss: https://kauth.kakao.com
      aud: ENC(9A0tR+kkLaKN+sWvP4+ZG65f6fBxRk+OcbGk99Nmz/B4R9GQra6PsYGoZuQ3LFPp)
    apple:
      iss: https://appleid.apple.com
      aud: ENC(7ZIvlhkgojaZtxgAjIWC5lrZDaygX7Pe)
    google:
      iss: https://accounts.google.com
      aud: ENC(Y/opa61EwfoNFAaNbdJPF18I/jRgQOuNtfbt8yQaVeoNxprdIrROTuYj/Yvsoq8InT0DRBMMDm5C0WHNu5d2KPfERZ4kJhYlm+CnouF+jng1ZDh9XD8SdQ==)

open-id-connect:
  kakao: https://kauth.kakao.com
  apple: https://appleid.apple.com
  google: https://www.googleapis.com